tag_page_layout: tag_page
tag_page_dir: tag
paginate: 10
pygments: true
markdown: rdiscount
lsi: false
url: http://unethicalblogger.com
exclude: ['README.markdown', 'drupal.rb', 'sync.sh', 'Makefile']
