name: 'rtyler'
description: 'a moderately technical blog'
tag_page_layout: tag_page
tag_page_dir: tag

paginate: 10
highlighter: 'rouge'
incremental: true
plugins:
  - jekyll-paginate
  - jekyll-include-cache

lsi: false
exclude:
  - README.markdown
  - Makefile
  - generate-tags
  - .jekyll-cache

# Used for the RSS feed generator
url: 'https://brokenco.de/'
author: 'R. Tyler Croy'

# Navigation
nav:
  - name:           "about"
    href:           "/about"
  - name:           "code"
    href:           "//github.com/rtyler"
  - name:           "feed"
    href:           '/atom.xml'

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

collections:
  microblog:
    output: true
    permalink: /microblog/:year/:month/:slug/
